### ISSUE TITLE
Bug: multigraph(..., directed=FALSE) failing for unknown reasons

### ISSUE THREAD

**Issue by skiaphrene** [mplex/multigraph#1]
Dear Antonio Rivero Ostoic,

First of all, thanks for package multigraph! Besides this bug I am enjoying using it!

The bug I've found happens when I try to create a multigraph plot of an array of dimensions 47x47x4. I have tried to figure out where it is coming from but have not been able to do so.
# Error message

The error message is this:

```
multigraph(net=tmp, layout = "stress", directed = FALSE)
Error in strsplit(y[i], prsep) : non-character argument
```

I have looked in the multigraph code and have not found this call, so I'm supposing it's coming from one of the dependencies.
# Things tried that work

However, changing some things around allows the code to run (albeit not as I would want):

```
multigraph(net=tmp, layout = "stress", directed = TRUE)
```

=> works fine!

This is true for all 3 layout options.

Also, the following calls also work:

```
multigraph(net=tmp[,,1:3], layout = "stress", directed = TRUE) # remove one of the layers => works
multigraph(net=tmp[1:25,1:25,], layout = "stress", directed = TRUE) # keep less than 25 nodes but all layers => works
```
# Workaround

As you can imagine, I'm quite confused! For now, flattening two layers together seems to me like the easiest workaround, but do you think you can correct this?

Thanks in advance for your help!

Best regards,

-- Alex

**Comment by mplex** [comment]
Dear Alex,

Thanks for your mail and for the notification error. This looks like a bug, absolutely.

However, it is hard to correct the bug without having more precise information. You say that the function works fine with directed graph, so the problem might be in retrieving the dyadic bundles when reciprocals are collapsed, which is the default option in `multigraph`.

You can try the below option and if this works fine, my guess is that you have patterns with at least two mutual ties.

    multigraph(net=tmp, layout = "stress", directed = FALSE, collRecip = FALSE)


Please let me know the result, and if for some reason you are unable to send the input data, it will be very helpful to count at least have the bundles to correct the bug. By switching off the `lb2lb` argument in the `bundles` function; all node labels from your network are replaced by identifiers.

    multiplex::bundles(net=tmp, lb2lb = FALSE)

or just the _reciprocal_ dyads from your network

    multiplex::bundles(net=tmp, lb2lb = FALSE)$recp

Thanks again and I hope to hearing from you.


Cheers,
Antonio

**Comment by mplex** [comment]
Dear Alex

Thanks for your mail and for the notification error. This looks like a bug, absolutely.

I created a data set, and I found a bug that can loose the issue you mention. The problem was located in a dependent function from the `multiplex` package related to the bundles. I made the adjustments, and now the fixed version (_13-sep_) has been uploaded on Github.

You need to remove the current version of `multiplex` from your computer and install the dev version

```
library(devtools)
devtools::install_github("mplex/multiplex")
```

I hope it works now. If not, please let me know.

Cheers,
Antonio

**Comment by skiaphrene** [comment]
Dear Antonio,

Thanks for your replies! 
I've installed your latest dev version and it does indeed work! I can now have 4 layers at the same time. The workaround still works, too.

Thanks a lot again & best regards,

-- Alex

**Comment by mplex** [comment]
Dear Alex,

Thanks a lot for getting back to me, and I am happy to hear that the package is working fine.

Just in case, after uploading v2.1 of **`multiplex`** into CRAN, I realized that _n_-tuple entrainments for _n>3_ are reported as mixed patterns as well. This does not have any consequence in the plotting of the multigraph, but the GITHUB version of this package corrects that, and the plotting should result being a little bit faster.

/Antonio
